import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Navbar from "./Navbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${inter.variable} suppressHydrationWarning={true} antialiased`}
      >
        <Theme accentColor="teal" radius="small">
          <Navbar />
          <main className="px-5 max-w-[1440px] mx-auto">{children}</main>
        </Theme>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
